name: Label PR on Merge Bot Action

on:
  pull_request:
    types: [ closed ]

jobs:
  label_pr_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Label PR on Merge Bot
        uses: abhijithvijayan/label-pr-on-merge-bot@v2
        with:
          GITHUB_TOKEN: ${{ secrets.PAT_LABEL }}
          merged_label: 'ðŸš€ merged'
